version: '3.3'
services:
  mcp_db:
    image: mysql:5.6
    hostname: mcp_db
    ports:
     - 3306:32769
    volumes:
     - ./data/mcp_db:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=limpid@123
      - MYSQL_DATABASE=mcp
      - MYSQL_USER=limpid
      - MYSQL_PASSWORD=limpid@123
  processor:
    build: .
    environment:
      - ENV=DEV
      - USERNAME=dev
      - PASSWORD=
      - LABID=254
      - MYSQL_HOST=mcp_db
      - MYSQL_ROOT_PASSWORD=limpid@123
      - MYSQL_DATABASE=mcp
      - MYSQL_USERNAME=limpid
      - MYSQL_PASSWORD=limpid@123      
    links:
     - mcp_db
    depends_on:
     - mcp_db
    ports:
     - 8080:8080
    tty: true
    stdin_open: true
    restart: always
